resolver: lts-9.21
packages: []

extra-deps:
- diagrams-pgf-1.4
- multiset-comb-0.2.4.1
- texrunner-0.0.1.1
- palette-0.1.0.5
- diagrams-core-1.4.0.1
- diagrams-lib-1.4.2
- diagrams-contrib-1.4.1
- SVGFonts-1.6.0.3
- shake-0.16
- diagrams-builder-0.8.0.2
- lhs2tex-1.20
- Agda-2.5.3

flags:
  diagrams-builder:
    pgf: true